name = "KnetterCraft"
author = "Sharqy"
version = "26.1-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69e832d730bd0596a9048ab57dd9c4ec8dc9ed32bbff31491bf0f728730b83da"

[versions]
minecraft = "26.1"
neoforge = "26.1.0.19-beta"
