name = "KnetterCraft"
author = "Sharqy"
version = "26.1-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9271a1e79e11539b2dcf6fecb297539b13522d85335e361965dce670a842c3cb"

[versions]
minecraft = "26.1"
neoforge = "26.1.0.19-beta"
