name = "KnetterCraft"
author = "Sharqy"
version = "26.1-dev"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "763b7fdba9cdb6adf5093488f1602afde232731ae1578fb49832a3daf03aafc4"

[versions]
minecraft = "26.1"
neoforge = "26.1.0.19-beta"
