Welcome Message:false
Zoom Level:3
Old North:false
Color Picker Mode:0
Hide Minimap:false
Update Notifier:false
Display Biome:false
Display Coordinates:0
Map Corner:1
Map Size:0
Square Map:true
Rotation:true
Waypoint Beacons:false
Waypoint Signs:true
Enable Cave Mode:true
Move Map Below Status Effect Icons:true
Move Scoreboard Below Map:true
Dynamic Lighting:true
Height Map:true
Slope Map:true
Water Transparency:true
Block Transparency:true
Biomes:true
Biome Overlay:0
Chunk Grid:false
Slime Chunks:false
World Border:true
Filtering:false
Teleport Command:tp %p %x %y %z
Waypoint Sort By:1
Waypoint Max Distance:-1
Waypoint Sign Scale:1.0
Deathpoints:1
Waypoint Distance Unit Conversion:1
Show In-game Waypoint Names:2
Show In-game Waypoint Distances:2
Zoom Key:key.keyboard.unknown
Fullscreen Key:key.keyboard.unknown
Menu Key:key.keyboard.m
Waypoint Menu Key:key.keyboard.u
Waypoint Key:key.keyboard.n
Mob Key:key.keyboard.unknown
In-game Waypoint Key:key.keyboard.unknown
Toggle Minimap Key:key.keyboard.unknown
Radar Mode:2
Show Radar:true
Show Hostiles:false
Show Neutrals:false
Show Players:true
Filter Mob Icons:true
Outline Mob Icons:true
Show Player Helmets:true
Show Mob Helmets:true
Show Player Names:true
Show Mob Names:true
Font Scale:1.0
Show Facing:true
Radar CPU Rendering:false
Show Full Entity Names:false
Show Entity Elevation:true
Hide Sneaking Players:true
Hide Invisible Entities:true
Hidden Mobs:
Worldmap Zoom:2
Worldmap Minimum Zoom:0.5
Worldmap Maximum Zoom:16.0
Worldmap Cache Size:500
Show Worldmap Coordinates:true
Show Worldmap Waypoints:true
Show Worldmap Waypoint Names:true
Show Worldmap Distant Waypoints:true
